// Generated by tools/generate_editor_icons.py.
ImVec4 IconColor(Icon icon) { switch(icon) {
case Icon::Save: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Undo: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Redo: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Play: return ImVec4{0.262745f,0.850980f,0.674510f,1.0f};
case Icon::Pause: return ImVec4{0.949020f,0.772549f,0.400000f,1.0f};
case Icon::Step: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Stop: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Select: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Move: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Rotate: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Scale: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Frame: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Focus: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Grid: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::List: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Entity: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Hierarchy: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Inspector: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Transform: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Texture: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Script: return ImVec4{0.262745f,0.850980f,0.674510f,1.0f};
case Icon::Animation: return ImVec4{0.737255f,0.627451f,0.960784f,1.0f};
case Icon::Audio: return ImVec4{0.949020f,0.772549f,0.400000f,1.0f};
case Icon::Font: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Camera: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Canvas: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Collider: return ImVec4{0.262745f,0.850980f,0.674510f,1.0f};
case Icon::Physics: return ImVec4{0.949020f,0.772549f,0.400000f,1.0f};
case Icon::Prefab: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Folder: return ImVec4{0.949020f,0.772549f,0.400000f,1.0f};
case Icon::Settings: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Search: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Add: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Delete: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Console: return ImVec4{0.725490f,0.784314f,0.847059f,1.0f};
case Icon::Info: return ImVec4{0.396078f,0.717647f,0.952941f,1.0f};
case Icon::Warning: return ImVec4{0.949020f,0.772549f,0.400000f,1.0f};
case Icon::Error: return ImVec4{0.945098f,0.482353f,0.509804f,1.0f};
case Icon::Agent: return ImVec4{0.737255f,0.627451f,0.960784f,1.0f};
case Icon::Profiler: return ImVec4{0.262745f,0.850980f,0.674510f,1.0f};
} return ImVec4{1,1,1,1}; }
void DrawIcon(Icon icon, ImVec2 origin, float size) {
if(size <= 0) return;
auto* draw = ImGui::GetWindowDrawList();
const float scale=size/24.0f;
const float stroke=2.0f*scale;
const ImU32 color=ImGui::GetColorU32(IconColor(icon));
auto P=[&](float x,float y){return ImVec2{origin.x+x*scale,origin.y+y*scale};};
switch(icon) {
case Icon::Save: {
draw->AddLine(P(4,3),P(17,3),color,stroke);
draw->AddLine(P(17,3),P(21,7),color,stroke);
draw->AddLine(P(21,7),P(21,21),color,stroke);
draw->AddLine(P(21,21),P(3,21),color,stroke);
draw->AddLine(P(3,21),P(3,3),color,stroke);
draw->AddLine(P(3,3),P(4,3),color,stroke);
draw->AddCircleFilled(P(4,3),stroke/2,color,8);
draw->AddCircleFilled(P(17,3),stroke/2,color,8);
draw->AddCircleFilled(P(21,7),stroke/2,color,8);
draw->AddCircleFilled(P(21,21),stroke/2,color,8);
draw->AddCircleFilled(P(3,21),stroke/2,color,8);
draw->AddCircleFilled(P(3,3),stroke/2,color,8);
draw->AddRect(P(7,3),P(16,9),color,0.0f*scale,0,stroke);
draw->AddRect(P(7,14),P(17,21),color,0.0f*scale,0,stroke);
break;}
case Icon::Undo: {
draw->AddLine(P(9,4),P(3,10),color,stroke);
draw->AddLine(P(3,10),P(9,16),color,stroke);
draw->AddCircleFilled(P(9,4),stroke/2,color,8);
draw->AddCircleFilled(P(3,10),stroke/2,color,8);
draw->AddCircleFilled(P(9,16),stroke/2,color,8);
draw->AddLine(P(3,10),P(14,10),color,stroke);
draw->AddLine(P(14,10),P(19,13),color,stroke);
draw->AddLine(P(19,13),P(20,18),color,stroke);
draw->AddCircleFilled(P(3,10),stroke/2,color,8);
draw->AddCircleFilled(P(14,10),stroke/2,color,8);
draw->AddCircleFilled(P(19,13),stroke/2,color,8);
draw->AddCircleFilled(P(20,18),stroke/2,color,8);
break;}
case Icon::Redo: {
draw->AddLine(P(15,4),P(21,10),color,stroke);
draw->AddLine(P(21,10),P(15,16),color,stroke);
draw->AddCircleFilled(P(15,4),stroke/2,color,8);
draw->AddCircleFilled(P(21,10),stroke/2,color,8);
draw->AddCircleFilled(P(15,16),stroke/2,color,8);
draw->AddLine(P(21,10),P(10,10),color,stroke);
draw->AddLine(P(10,10),P(5,13),color,stroke);
draw->AddLine(P(5,13),P(4,18),color,stroke);
draw->AddCircleFilled(P(21,10),stroke/2,color,8);
draw->AddCircleFilled(P(10,10),stroke/2,color,8);
draw->AddCircleFilled(P(5,13),stroke/2,color,8);
draw->AddCircleFilled(P(4,18),stroke/2,color,8);
break;}
case Icon::Play: {
{const ImVec2 points[]{P(6,3),P(21,12),P(6,21)};draw->AddConvexPolyFilled(points,IM_ARRAYSIZE(points),color);}
break;}
case Icon::Pause: {
draw->AddRect(P(5,4),P(9,20),color,0.5f*scale,0,stroke);
draw->AddRect(P(15,4),P(19,20),color,0.5f*scale,0,stroke);
break;}
case Icon::Step: {
{const ImVec2 points[]{P(4,4),P(15,12),P(4,20)};draw->AddConvexPolyFilled(points,IM_ARRAYSIZE(points),color);}
draw->AddRect(P(18,4),P(21,20),color,0.5f*scale,0,stroke);
break;}
case Icon::Stop: {
draw->AddRect(P(5,5),P(19,19),color,1.0f*scale,0,stroke);
break;}
case Icon::Select: {
draw->AddLine(P(5,3),P(19,13),color,stroke);
draw->AddLine(P(19,13),P(13,14),color,stroke);
draw->AddLine(P(13,14),P(10,21),color,stroke);
draw->AddLine(P(10,21),P(5,3),color,stroke);
draw->AddLine(P(5,3),P(5,3),color,stroke);
draw->AddCircleFilled(P(5,3),stroke/2,color,8);
draw->AddCircleFilled(P(19,13),stroke/2,color,8);
draw->AddCircleFilled(P(13,14),stroke/2,color,8);
draw->AddCircleFilled(P(10,21),stroke/2,color,8);
draw->AddCircleFilled(P(5,3),stroke/2,color,8);
break;}
case Icon::Move: {
draw->AddLine(P(12,3),P(12,21),color,stroke);
draw->AddCircleFilled(P(12,3),stroke/2,color,8);
draw->AddCircleFilled(P(12,21),stroke/2,color,8);
draw->AddLine(P(3,12),P(21,12),color,stroke);
draw->AddCircleFilled(P(3,12),stroke/2,color,8);
draw->AddCircleFilled(P(21,12),stroke/2,color,8);
draw->AddLine(P(9,6),P(12,3),color,stroke);
draw->AddLine(P(12,3),P(15,6),color,stroke);
draw->AddCircleFilled(P(9,6),stroke/2,color,8);
draw->AddCircleFilled(P(12,3),stroke/2,color,8);
draw->AddCircleFilled(P(15,6),stroke/2,color,8);
draw->AddLine(P(9,18),P(12,21),color,stroke);
draw->AddLine(P(12,21),P(15,18),color,stroke);
draw->AddCircleFilled(P(9,18),stroke/2,color,8);
draw->AddCircleFilled(P(12,21),stroke/2,color,8);
draw->AddCircleFilled(P(15,18),stroke/2,color,8);
draw->AddLine(P(6,9),P(3,12),color,stroke);
draw->AddLine(P(3,12),P(6,15),color,stroke);
draw->AddCircleFilled(P(6,9),stroke/2,color,8);
draw->AddCircleFilled(P(3,12),stroke/2,color,8);
draw->AddCircleFilled(P(6,15),stroke/2,color,8);
draw->AddLine(P(18,9),P(21,12),color,stroke);
draw->AddLine(P(21,12),P(18,15),color,stroke);
draw->AddCircleFilled(P(18,9),stroke/2,color,8);
draw->AddCircleFilled(P(21,12),stroke/2,color,8);
draw->AddCircleFilled(P(18,15),stroke/2,color,8);
break;}
case Icon::Rotate: {
draw->AddLine(P(19,7),P(15,3),color,stroke);
draw->AddLine(P(15,3),P(8,3),color,stroke);
draw->AddLine(P(8,3),P(3,8),color,stroke);
draw->AddLine(P(3,8),P(3,16),color,stroke);
draw->AddLine(P(3,16),P(8,21),color,stroke);
draw->AddLine(P(8,21),P(16,21),color,stroke);
draw->AddLine(P(16,21),P(21,16),color,stroke);
draw->AddCircleFilled(P(19,7),stroke/2,color,8);
draw->AddCircleFilled(P(15,3),stroke/2,color,8);
draw->AddCircleFilled(P(8,3),stroke/2,color,8);
draw->AddCircleFilled(P(3,8),stroke/2,color,8);
draw->AddCircleFilled(P(3,16),stroke/2,color,8);
draw->AddCircleFilled(P(8,21),stroke/2,color,8);
draw->AddCircleFilled(P(16,21),stroke/2,color,8);
draw->AddCircleFilled(P(21,16),stroke/2,color,8);
draw->AddLine(P(19,2),P(19,7),color,stroke);
draw->AddLine(P(19,7),P(14,7),color,stroke);
draw->AddCircleFilled(P(19,2),stroke/2,color,8);
draw->AddCircleFilled(P(19,7),stroke/2,color,8);
draw->AddCircleFilled(P(14,7),stroke/2,color,8);
break;}
case Icon::Scale: {
draw->AddRect(P(3,13),P(11,21),color,0.0f*scale,0,stroke);
draw->AddLine(P(11,13),P(21,3),color,stroke);
draw->AddCircleFilled(P(11,13),stroke/2,color,8);
draw->AddCircleFilled(P(21,3),stroke/2,color,8);
draw->AddLine(P(14,3),P(21,3),color,stroke);
draw->AddLine(P(21,3),P(21,10),color,stroke);
draw->AddCircleFilled(P(14,3),stroke/2,color,8);
draw->AddCircleFilled(P(21,3),stroke/2,color,8);
draw->AddCircleFilled(P(21,10),stroke/2,color,8);
break;}
case Icon::Frame: {
draw->AddLine(P(3,9),P(3,3),color,stroke);
draw->AddLine(P(3,3),P(9,3),color,stroke);
draw->AddCircleFilled(P(3,9),stroke/2,color,8);
draw->AddCircleFilled(P(3,3),stroke/2,color,8);
draw->AddCircleFilled(P(9,3),stroke/2,color,8);
draw->AddLine(P(15,3),P(21,3),color,stroke);
draw->AddLine(P(21,3),P(21,9),color,stroke);
draw->AddCircleFilled(P(15,3),stroke/2,color,8);
draw->AddCircleFilled(P(21,3),stroke/2,color,8);
draw->AddCircleFilled(P(21,9),stroke/2,color,8);
draw->AddLine(P(21,15),P(21,21),color,stroke);
draw->AddLine(P(21,21),P(15,21),color,stroke);
draw->AddCircleFilled(P(21,15),stroke/2,color,8);
draw->AddCircleFilled(P(21,21),stroke/2,color,8);
draw->AddCircleFilled(P(15,21),stroke/2,color,8);
draw->AddLine(P(9,21),P(3,21),color,stroke);
draw->AddLine(P(3,21),P(3,15),color,stroke);
draw->AddCircleFilled(P(9,21),stroke/2,color,8);
draw->AddCircleFilled(P(3,21),stroke/2,color,8);
draw->AddCircleFilled(P(3,15),stroke/2,color,8);
draw->AddRect(P(8,8),P(16,16),color,0.0f*scale,0,stroke);
break;}
case Icon::Focus: {
draw->AddCircle(P(12,12),7.0f*scale,color,0,stroke);
draw->AddLine(P(12,2),P(12,7),color,stroke);
draw->AddCircleFilled(P(12,2),stroke/2,color,8);
draw->AddCircleFilled(P(12,7),stroke/2,color,8);
draw->AddLine(P(12,17),P(12,22),color,stroke);
draw->AddCircleFilled(P(12,17),stroke/2,color,8);
draw->AddCircleFilled(P(12,22),stroke/2,color,8);
draw->AddLine(P(2,12),P(7,12),color,stroke);
draw->AddCircleFilled(P(2,12),stroke/2,color,8);
draw->AddCircleFilled(P(7,12),stroke/2,color,8);
draw->AddLine(P(17,12),P(22,12),color,stroke);
draw->AddCircleFilled(P(17,12),stroke/2,color,8);
draw->AddCircleFilled(P(22,12),stroke/2,color,8);
break;}
case Icon::Grid: {
draw->AddRect(P(3,3),P(21,21),color,0.0f*scale,0,stroke);
draw->AddLine(P(9,3),P(9,21),color,stroke);
draw->AddCircleFilled(P(9,3),stroke/2,color,8);
draw->AddCircleFilled(P(9,21),stroke/2,color,8);
draw->AddLine(P(15,3),P(15,21),color,stroke);
draw->AddCircleFilled(P(15,3),stroke/2,color,8);
draw->AddCircleFilled(P(15,21),stroke/2,color,8);
draw->AddLine(P(3,9),P(21,9),color,stroke);
draw->AddCircleFilled(P(3,9),stroke/2,color,8);
draw->AddCircleFilled(P(21,9),stroke/2,color,8);
draw->AddLine(P(3,15),P(21,15),color,stroke);
draw->AddCircleFilled(P(3,15),stroke/2,color,8);
draw->AddCircleFilled(P(21,15),stroke/2,color,8);
break;}
case Icon::List: {
draw->AddLine(P(9,5),P(21,5),color,stroke);
draw->AddCircleFilled(P(9,5),stroke/2,color,8);
draw->AddCircleFilled(P(21,5),stroke/2,color,8);
draw->AddLine(P(9,12),P(21,12),color,stroke);
draw->AddCircleFilled(P(9,12),stroke/2,color,8);
draw->AddCircleFilled(P(21,12),stroke/2,color,8);
draw->AddLine(P(9,19),P(21,19),color,stroke);
draw->AddCircleFilled(P(9,19),stroke/2,color,8);
draw->AddCircleFilled(P(21,19),stroke/2,color,8);
draw->AddRect(P(3,4),P(5,6),color,0.0f*scale,0,stroke);
draw->AddRect(P(3,11),P(5,13),color,0.0f*scale,0,stroke);
draw->AddRect(P(3,18),P(5,20),color,0.0f*scale,0,stroke);
break;}
case Icon::Entity: {
draw->AddLine(P(12,2),P(21,7),color,stroke);
draw->AddLine(P(21,7),P(21,17),color,stroke);
draw->AddLine(P(21,17),P(12,22),color,stroke);
draw->AddLine(P(12,22),P(3,17),color,stroke);
draw->AddLine(P(3,17),P(3,7),color,stroke);
draw->AddLine(P(3,7),P(12,2),color,stroke);
draw->AddCircleFilled(P(12,2),stroke/2,color,8);
draw->AddCircleFilled(P(21,7),stroke/2,color,8);
draw->AddCircleFilled(P(21,17),stroke/2,color,8);
draw->AddCircleFilled(P(12,22),stroke/2,color,8);
draw->AddCircleFilled(P(3,17),stroke/2,color,8);
draw->AddCircleFilled(P(3,7),stroke/2,color,8);
draw->AddLine(P(3,7),P(12,12),color,stroke);
draw->AddLine(P(12,12),P(21,7),color,stroke);
draw->AddCircleFilled(P(3,7),stroke/2,color,8);
draw->AddCircleFilled(P(12,12),stroke/2,color,8);
draw->AddCircleFilled(P(21,7),stroke/2,color,8);
draw->AddLine(P(12,12),P(12,22),color,stroke);
draw->AddCircleFilled(P(12,12),stroke/2,color,8);
draw->AddCircleFilled(P(12,22),stroke/2,color,8);
break;}
case Icon::Hierarchy: {
draw->AddRect(P(8,2),P(16,7),color,1.0f*scale,0,stroke);
draw->AddRect(P(2,17),P(9,22),color,1.0f*scale,0,stroke);
draw->AddRect(P(15,17),P(22,22),color,1.0f*scale,0,stroke);
draw->AddLine(P(12,7),P(12,12),color,stroke);
draw->AddLine(P(12,12),P(5,12),color,stroke);
draw->AddLine(P(5,12),P(5,17),color,stroke);
draw->AddCircleFilled(P(12,7),stroke/2,color,8);
draw->AddCircleFilled(P(12,12),stroke/2,color,8);
draw->AddCircleFilled(P(5,12),stroke/2,color,8);
draw->AddCircleFilled(P(5,17),stroke/2,color,8);
draw->AddLine(P(12,12),P(19,12),color,stroke);
draw->AddLine(P(19,12),P(19,17),color,stroke);
draw->AddCircleFilled(P(12,12),stroke/2,color,8);
draw->AddCircleFilled(P(19,12),stroke/2,color,8);
draw->AddCircleFilled(P(19,17),stroke/2,color,8);
break;}
case Icon::Inspector: {
draw->AddLine(P(3,5),P(21,5),color,stroke);
draw->AddCircleFilled(P(3,5),stroke/2,color,8);
draw->AddCircleFilled(P(21,5),stroke/2,color,8);
draw->AddLine(P(3,12),P(21,12),color,stroke);
draw->AddCircleFilled(P(3,12),stroke/2,color,8);
draw->AddCircleFilled(P(21,12),stroke/2,color,8);
draw->AddLine(P(3,19),P(21,19),color,stroke);
draw->AddCircleFilled(P(3,19),stroke/2,color,8);
draw->AddCircleFilled(P(21,19),stroke/2,color,8);
draw->AddRect(P(7,2),P(11,8),color,1.0f*scale,0,stroke);
draw->AddRect(P(15,9),P(19,15),color,1.0f*scale,0,stroke);
draw->AddRect(P(6,16),P(10,22),color,1.0f*scale,0,stroke);
break;}
case Icon::Transform: {
draw->AddLine(P(5,20),P(5,3),color,stroke);
draw->AddCircleFilled(P(5,20),stroke/2,color,8);
draw->AddCircleFilled(P(5,3),stroke/2,color,8);
draw->AddLine(P(5,20),P(21,20),color,stroke);
draw->AddCircleFilled(P(5,20),stroke/2,color,8);
draw->AddCircleFilled(P(21,20),stroke/2,color,8);
draw->AddLine(P(2,6),P(5,3),color,stroke);
draw->AddLine(P(5,3),P(8,6),color,stroke);
draw->AddCircleFilled(P(2,6),stroke/2,color,8);
draw->AddCircleFilled(P(5,3),stroke/2,color,8);
draw->AddCircleFilled(P(8,6),stroke/2,color,8);
draw->AddLine(P(18,17),P(21,20),color,stroke);
draw->AddLine(P(21,20),P(18,23),color,stroke);
draw->AddCircleFilled(P(18,17),stroke/2,color,8);
draw->AddCircleFilled(P(21,20),stroke/2,color,8);
draw->AddCircleFilled(P(18,23),stroke/2,color,8);
draw->AddLine(P(5,20),P(15,10),color,stroke);
draw->AddCircleFilled(P(5,20),stroke/2,color,8);
draw->AddCircleFilled(P(15,10),stroke/2,color,8);
draw->AddLine(P(10,10),P(15,10),color,stroke);
draw->AddLine(P(15,10),P(15,15),color,stroke);
draw->AddCircleFilled(P(10,10),stroke/2,color,8);
draw->AddCircleFilled(P(15,10),stroke/2,color,8);
draw->AddCircleFilled(P(15,15),stroke/2,color,8);
break;}
case Icon::Texture: {
draw->AddRect(P(3,3),P(21,21),color,1.0f*scale,0,stroke);
draw->AddCircle(P(8,8),2.0f*scale,color,0,stroke);
draw->AddLine(P(3,18),P(9,12),color,stroke);
draw->AddLine(P(9,12),P(13,16),color,stroke);
draw->AddLine(P(13,16),P(17,10),color,stroke);
draw->AddLine(P(17,10),P(21,15),color,stroke);
draw->AddCircleFilled(P(3,18),stroke/2,color,8);
draw->AddCircleFilled(P(9,12),stroke/2,color,8);
draw->AddCircleFilled(P(13,16),stroke/2,color,8);
draw->AddCircleFilled(P(17,10),stroke/2,color,8);
draw->AddCircleFilled(P(21,15),stroke/2,color,8);
break;}
case Icon::Script: {
draw->AddLine(P(8,5),P(2,12),color,stroke);
draw->AddLine(P(2,12),P(8,19),color,stroke);
draw->AddCircleFilled(P(8,5),stroke/2,color,8);
draw->AddCircleFilled(P(2,12),stroke/2,color,8);
draw->AddCircleFilled(P(8,19),stroke/2,color,8);
draw->AddLine(P(16,5),P(22,12),color,stroke);
draw->AddLine(P(22,12),P(16,19),color,stroke);
draw->AddCircleFilled(P(16,5),stroke/2,color,8);
draw->AddCircleFilled(P(22,12),stroke/2,color,8);
draw->AddCircleFilled(P(16,19),stroke/2,color,8);
draw->AddLine(P(14,3),P(10,21),color,stroke);
draw->AddCircleFilled(P(14,3),stroke/2,color,8);
draw->AddCircleFilled(P(10,21),stroke/2,color,8);
break;}
case Icon::Animation: {
draw->AddRect(P(3,5),P(21,21),color,1.0f*scale,0,stroke);
draw->AddLine(P(3,10),P(21,10),color,stroke);
draw->AddCircleFilled(P(3,10),stroke/2,color,8);
draw->AddCircleFilled(P(21,10),stroke/2,color,8);
draw->AddLine(P(7,5),P(10,10),color,stroke);
draw->AddCircleFilled(P(7,5),stroke/2,color,8);
draw->AddCircleFilled(P(10,10),stroke/2,color,8);
draw->AddLine(P(13,5),P(16,10),color,stroke);
draw->AddCircleFilled(P(13,5),stroke/2,color,8);
draw->AddCircleFilled(P(16,10),stroke/2,color,8);
{const ImVec2 points[]{P(9,13),P(15,16),P(9,19)};draw->AddConvexPolyFilled(points,IM_ARRAYSIZE(points),color);}
break;}
case Icon::Audio: {
draw->AddLine(P(9,17),P(9,5),color,stroke);
draw->AddLine(P(9,5),P(20,3),color,stroke);
draw->AddLine(P(20,3),P(20,15),color,stroke);
draw->AddCircleFilled(P(9,17),stroke/2,color,8);
draw->AddCircleFilled(P(9,5),stroke/2,color,8);
draw->AddCircleFilled(P(20,3),stroke/2,color,8);
draw->AddCircleFilled(P(20,15),stroke/2,color,8);
draw->AddLine(P(9,9),P(20,7),color,stroke);
draw->AddCircleFilled(P(9,9),stroke/2,color,8);
draw->AddCircleFilled(P(20,7),stroke/2,color,8);
draw->AddCircle(P(6,18),3.0f*scale,color,0,stroke);
draw->AddCircle(P(17,16),3.0f*scale,color,0,stroke);
break;}
case Icon::Font: {
draw->AddLine(P(3,6),P(3,3),color,stroke);
draw->AddLine(P(3,3),P(21,3),color,stroke);
draw->AddLine(P(21,3),P(21,6),color,stroke);
draw->AddCircleFilled(P(3,6),stroke/2,color,8);
draw->AddCircleFilled(P(3,3),stroke/2,color,8);
draw->AddCircleFilled(P(21,3),stroke/2,color,8);
draw->AddCircleFilled(P(21,6),stroke/2,color,8);
draw->AddLine(P(12,3),P(12,21),color,stroke);
draw->AddCircleFilled(P(12,3),stroke/2,color,8);
draw->AddCircleFilled(P(12,21),stroke/2,color,8);
draw->AddLine(P(7,21),P(17,21),color,stroke);
draw->AddCircleFilled(P(7,21),stroke/2,color,8);
draw->AddCircleFilled(P(17,21),stroke/2,color,8);
break;}
case Icon::Camera: {
draw->AddRect(P(2,6),P(16,19),color,1.0f*scale,0,stroke);
draw->AddLine(P(16,10),P(22,6),color,stroke);
draw->AddLine(P(22,6),P(22,19),color,stroke);
draw->AddLine(P(22,19),P(16,15),color,stroke);
draw->AddLine(P(16,15),P(16,10),color,stroke);
draw->AddCircleFilled(P(16,10),stroke/2,color,8);
draw->AddCircleFilled(P(22,6),stroke/2,color,8);
draw->AddCircleFilled(P(22,19),stroke/2,color,8);
draw->AddCircleFilled(P(16,15),stroke/2,color,8);
break;}
case Icon::Canvas: {
draw->AddRect(P(2,3),P(22,19),color,1.0f*scale,0,stroke);
draw->AddLine(P(8,22),P(16,22),color,stroke);
draw->AddCircleFilled(P(8,22),stroke/2,color,8);
draw->AddCircleFilled(P(16,22),stroke/2,color,8);
draw->AddLine(P(12,19),P(12,22),color,stroke);
draw->AddCircleFilled(P(12,19),stroke/2,color,8);
draw->AddCircleFilled(P(12,22),stroke/2,color,8);
draw->AddRect(P(5,6),P(10,15),color,0.0f*scale,0,stroke);
draw->AddLine(P(13,7),P(19,7),color,stroke);
draw->AddCircleFilled(P(13,7),stroke/2,color,8);
draw->AddCircleFilled(P(19,7),stroke/2,color,8);
draw->AddLine(P(13,11),P(19,11),color,stroke);
draw->AddCircleFilled(P(13,11),stroke/2,color,8);
draw->AddCircleFilled(P(19,11),stroke/2,color,8);
break;}
case Icon::Collider: {
draw->AddLine(P(8,3),P(3,3),color,stroke);
draw->AddLine(P(3,3),P(3,8),color,stroke);
draw->AddCircleFilled(P(8,3),stroke/2,color,8);
draw->AddCircleFilled(P(3,3),stroke/2,color,8);
draw->AddCircleFilled(P(3,8),stroke/2,color,8);
draw->AddLine(P(16,3),P(21,3),color,stroke);
draw->AddLine(P(21,3),P(21,8),color,stroke);
draw->AddCircleFilled(P(16,3),stroke/2,color,8);
draw->AddCircleFilled(P(21,3),stroke/2,color,8);
draw->AddCircleFilled(P(21,8),stroke/2,color,8);
draw->AddLine(P(21,16),P(21,21),color,stroke);
draw->AddLine(P(21,21),P(16,21),color,stroke);
draw->AddCircleFilled(P(21,16),stroke/2,color,8);
draw->AddCircleFilled(P(21,21),stroke/2,color,8);
draw->AddCircleFilled(P(16,21),stroke/2,color,8);
draw->AddLine(P(8,21),P(3,21),color,stroke);
draw->AddLine(P(3,21),P(3,16),color,stroke);
draw->AddCircleFilled(P(8,21),stroke/2,color,8);
draw->AddCircleFilled(P(3,21),stroke/2,color,8);
draw->AddCircleFilled(P(3,16),stroke/2,color,8);
draw->AddRect(P(7,7),P(17,17),color,0.0f*scale,0,stroke);
break;}
case Icon::Physics: {
draw->AddCircle(P(12,13),7.0f*scale,color,0,stroke);
draw->AddLine(P(12,3),P(12,13),color,stroke);
draw->AddLine(P(12,13),P(16,16),color,stroke);
draw->AddCircleFilled(P(12,3),stroke/2,color,8);
draw->AddCircleFilled(P(12,13),stroke/2,color,8);
draw->AddCircleFilled(P(16,16),stroke/2,color,8);
draw->AddLine(P(3,22),P(21,22),color,stroke);
draw->AddCircleFilled(P(3,22),stroke/2,color,8);
draw->AddCircleFilled(P(21,22),stroke/2,color,8);
draw->AddLine(P(9,2),P(15,2),color,stroke);
draw->AddCircleFilled(P(9,2),stroke/2,color,8);
draw->AddCircleFilled(P(15,2),stroke/2,color,8);
break;}
case Icon::Prefab: {
draw->AddLine(P(12,2),P(21,7),color,stroke);
draw->AddLine(P(21,7),P(21,17),color,stroke);
draw->AddLine(P(21,17),P(12,22),color,stroke);
draw->AddLine(P(12,22),P(3,17),color,stroke);
draw->AddLine(P(3,17),P(3,7),color,stroke);
draw->AddLine(P(3,7),P(12,2),color,stroke);
draw->AddCircleFilled(P(12,2),stroke/2,color,8);
draw->AddCircleFilled(P(21,7),stroke/2,color,8);
draw->AddCircleFilled(P(21,17),stroke/2,color,8);
draw->AddCircleFilled(P(12,22),stroke/2,color,8);
draw->AddCircleFilled(P(3,17),stroke/2,color,8);
draw->AddCircleFilled(P(3,7),stroke/2,color,8);
draw->AddLine(P(3,7),P(12,12),color,stroke);
draw->AddLine(P(12,12),P(21,7),color,stroke);
draw->AddCircleFilled(P(3,7),stroke/2,color,8);
draw->AddCircleFilled(P(12,12),stroke/2,color,8);
draw->AddCircleFilled(P(21,7),stroke/2,color,8);
draw->AddLine(P(12,12),P(12,22),color,stroke);
draw->AddCircleFilled(P(12,12),stroke/2,color,8);
draw->AddCircleFilled(P(12,22),stroke/2,color,8);
draw->AddLine(P(12,6),P(16,8),color,stroke);
draw->AddLine(P(16,8),P(12,10),color,stroke);
draw->AddLine(P(12,10),P(8,8),color,stroke);
draw->AddLine(P(8,8),P(12,6),color,stroke);
draw->AddCircleFilled(P(12,6),stroke/2,color,8);
draw->AddCircleFilled(P(16,8),stroke/2,color,8);
draw->AddCircleFilled(P(12,10),stroke/2,color,8);
draw->AddCircleFilled(P(8,8),stroke/2,color,8);
break;}
case Icon::Folder: {
draw->AddLine(P(3,5),P(9,5),color,stroke);
draw->AddLine(P(9,5),P(12,8),color,stroke);
draw->AddLine(P(12,8),P(21,8),color,stroke);
draw->AddLine(P(21,8),P(21,21),color,stroke);
draw->AddLine(P(21,21),P(3,21),color,stroke);
draw->AddLine(P(3,21),P(3,5),color,stroke);
draw->AddCircleFilled(P(3,5),stroke/2,color,8);
draw->AddCircleFilled(P(9,5),stroke/2,color,8);
draw->AddCircleFilled(P(12,8),stroke/2,color,8);
draw->AddCircleFilled(P(21,8),stroke/2,color,8);
draw->AddCircleFilled(P(21,21),stroke/2,color,8);
draw->AddCircleFilled(P(3,21),stroke/2,color,8);
draw->AddLine(P(3,11),P(21,11),color,stroke);
draw->AddCircleFilled(P(3,11),stroke/2,color,8);
draw->AddCircleFilled(P(21,11),stroke/2,color,8);
break;}
case Icon::Settings: {
draw->AddLine(P(9,2),P(15,2),color,stroke);
draw->AddLine(P(15,2),P(16,6),color,stroke);
draw->AddLine(P(16,6),P(20,6),color,stroke);
draw->AddLine(P(20,6),P(23,12),color,stroke);
draw->AddLine(P(23,12),P(20,18),color,stroke);
draw->AddLine(P(20,18),P(16,18),color,stroke);
draw->AddLine(P(16,18),P(15,22),color,stroke);
draw->AddLine(P(15,22),P(9,22),color,stroke);
draw->AddLine(P(9,22),P(8,18),color,stroke);
draw->AddLine(P(8,18),P(4,18),color,stroke);
draw->AddLine(P(4,18),P(1,12),color,stroke);
draw->AddLine(P(1,12),P(4,6),color,stroke);
draw->AddLine(P(4,6),P(8,6),color,stroke);
draw->AddLine(P(8,6),P(9,2),color,stroke);
draw->AddCircleFilled(P(9,2),stroke/2,color,8);
draw->AddCircleFilled(P(15,2),stroke/2,color,8);
draw->AddCircleFilled(P(16,6),stroke/2,color,8);
draw->AddCircleFilled(P(20,6),stroke/2,color,8);
draw->AddCircleFilled(P(23,12),stroke/2,color,8);
draw->AddCircleFilled(P(20,18),stroke/2,color,8);
draw->AddCircleFilled(P(16,18),stroke/2,color,8);
draw->AddCircleFilled(P(15,22),stroke/2,color,8);
draw->AddCircleFilled(P(9,22),stroke/2,color,8);
draw->AddCircleFilled(P(8,18),stroke/2,color,8);
draw->AddCircleFilled(P(4,18),stroke/2,color,8);
draw->AddCircleFilled(P(1,12),stroke/2,color,8);
draw->AddCircleFilled(P(4,6),stroke/2,color,8);
draw->AddCircleFilled(P(8,6),stroke/2,color,8);
draw->AddCircle(P(12,12),4.0f*scale,color,0,stroke);
break;}
case Icon::Search: {
draw->AddCircle(P(10,10),6.0f*scale,color,0,stroke);
draw->AddLine(P(15,15),P(21,21),color,stroke);
draw->AddCircleFilled(P(15,15),stroke/2,color,8);
draw->AddCircleFilled(P(21,21),stroke/2,color,8);
break;}
case Icon::Add: {
draw->AddLine(P(12,4),P(12,20),color,stroke);
draw->AddCircleFilled(P(12,4),stroke/2,color,8);
draw->AddCircleFilled(P(12,20),stroke/2,color,8);
draw->AddLine(P(4,12),P(20,12),color,stroke);
draw->AddCircleFilled(P(4,12),stroke/2,color,8);
draw->AddCircleFilled(P(20,12),stroke/2,color,8);
break;}
case Icon::Delete: {
draw->AddLine(P(3,6),P(21,6),color,stroke);
draw->AddCircleFilled(P(3,6),stroke/2,color,8);
draw->AddCircleFilled(P(21,6),stroke/2,color,8);
draw->AddLine(P(5,6),P(6,21),color,stroke);
draw->AddLine(P(6,21),P(18,21),color,stroke);
draw->AddLine(P(18,21),P(19,6),color,stroke);
draw->AddCircleFilled(P(5,6),stroke/2,color,8);
draw->AddCircleFilled(P(6,21),stroke/2,color,8);
draw->AddCircleFilled(P(18,21),stroke/2,color,8);
draw->AddCircleFilled(P(19,6),stroke/2,color,8);
draw->AddLine(P(8,6),P(8,3),color,stroke);
draw->AddLine(P(8,3),P(16,3),color,stroke);
draw->AddLine(P(16,3),P(16,6),color,stroke);
draw->AddCircleFilled(P(8,6),stroke/2,color,8);
draw->AddCircleFilled(P(8,3),stroke/2,color,8);
draw->AddCircleFilled(P(16,3),stroke/2,color,8);
draw->AddCircleFilled(P(16,6),stroke/2,color,8);
draw->AddLine(P(10,10),P(10,17),color,stroke);
draw->AddCircleFilled(P(10,10),stroke/2,color,8);
draw->AddCircleFilled(P(10,17),stroke/2,color,8);
draw->AddLine(P(14,10),P(14,17),color,stroke);
draw->AddCircleFilled(P(14,10),stroke/2,color,8);
draw->AddCircleFilled(P(14,17),stroke/2,color,8);
break;}
case Icon::Console: {
draw->AddRect(P(2,3),P(22,21),color,1.0f*scale,0,stroke);
draw->AddLine(P(6,8),P(10,12),color,stroke);
draw->AddLine(P(10,12),P(6,16),color,stroke);
draw->AddCircleFilled(P(6,8),stroke/2,color,8);
draw->AddCircleFilled(P(10,12),stroke/2,color,8);
draw->AddCircleFilled(P(6,16),stroke/2,color,8);
draw->AddLine(P(13,16),P(18,16),color,stroke);
draw->AddCircleFilled(P(13,16),stroke/2,color,8);
draw->AddCircleFilled(P(18,16),stroke/2,color,8);
break;}
case Icon::Info: {
draw->AddCircle(P(12,12),10.0f*scale,color,0,stroke);
draw->AddCircle(P(12,7),0.7f*scale,color,0,stroke);
draw->AddLine(P(12,11),P(12,17),color,stroke);
draw->AddCircleFilled(P(12,11),stroke/2,color,8);
draw->AddCircleFilled(P(12,17),stroke/2,color,8);
break;}
case Icon::Warning: {
draw->AddLine(P(12,2),P(23,21),color,stroke);
draw->AddLine(P(23,21),P(1,21),color,stroke);
draw->AddLine(P(1,21),P(12,2),color,stroke);
draw->AddCircleFilled(P(12,2),stroke/2,color,8);
draw->AddCircleFilled(P(23,21),stroke/2,color,8);
draw->AddCircleFilled(P(1,21),stroke/2,color,8);
draw->AddLine(P(12,8),P(12,13),color,stroke);
draw->AddCircleFilled(P(12,8),stroke/2,color,8);
draw->AddCircleFilled(P(12,13),stroke/2,color,8);
draw->AddCircle(P(12,17),0.7f*scale,color,0,stroke);
break;}
case Icon::Error: {
draw->AddCircle(P(12,12),10.0f*scale,color,0,stroke);
draw->AddLine(P(8,8),P(16,16),color,stroke);
draw->AddCircleFilled(P(8,8),stroke/2,color,8);
draw->AddCircleFilled(P(16,16),stroke/2,color,8);
draw->AddLine(P(16,8),P(8,16),color,stroke);
draw->AddCircleFilled(P(16,8),stroke/2,color,8);
draw->AddCircleFilled(P(8,16),stroke/2,color,8);
break;}
case Icon::Agent: {
draw->AddRect(P(3,7),P(21,21),color,3.0f*scale,0,stroke);
draw->AddLine(P(12,3),P(12,7),color,stroke);
draw->AddCircleFilled(P(12,3),stroke/2,color,8);
draw->AddCircleFilled(P(12,7),stroke/2,color,8);
draw->AddCircle(P(12,2),1.0f*scale,color,0,stroke);
draw->AddCircle(P(8,13),1.0f*scale,color,0,stroke);
draw->AddCircle(P(16,13),1.0f*scale,color,0,stroke);
draw->AddLine(P(8,17),P(16,17),color,stroke);
draw->AddCircleFilled(P(8,17),stroke/2,color,8);
draw->AddCircleFilled(P(16,17),stroke/2,color,8);
break;}
case Icon::Profiler: {
draw->AddLine(P(3,3),P(3,21),color,stroke);
draw->AddLine(P(3,21),P(22,21),color,stroke);
draw->AddCircleFilled(P(3,3),stroke/2,color,8);
draw->AddCircleFilled(P(3,21),stroke/2,color,8);
draw->AddCircleFilled(P(22,21),stroke/2,color,8);
draw->AddLine(P(6,16),P(10,11),color,stroke);
draw->AddLine(P(10,11),P(14,14),color,stroke);
draw->AddLine(P(14,14),P(21,5),color,stroke);
draw->AddCircleFilled(P(6,16),stroke/2,color,8);
draw->AddCircleFilled(P(10,11),stroke/2,color,8);
draw->AddCircleFilled(P(14,14),stroke/2,color,8);
draw->AddCircleFilled(P(21,5),stroke/2,color,8);
break;}
}}
