name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  windows-msvc:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install glad generator dependency
        run: python3 -m pip install jinja2

      - name: Configure
        run: cmake --preset windows-msvc-debug-tests

      - name: Build
        run: cmake --build --preset windows-msvc-debug-tests

      - name: Test
        run: ctest --preset windows-msvc-debug-tests
